[package]
name = "silent_payments_plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
silentpayments = { git = "https://github.com/cygnet3/rust-silentpayments", tag = "v0.4.0" }
serde_json = "1.0"
